-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 00:45:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema disney
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema disney
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `disney` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `disney` ;

-- -----------------------------------------------------
-- Table `disney`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`character` (
  `id_character` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `weight` DOUBLE NULL DEFAULT NULL,
  `history` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_character`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`movie` (
  `id_movie` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `creation_date` DATETIME NULL DEFAULT NULL,
  `rating` ENUM('1', '2', '3', '4', '5') NULL DEFAULT NULL,
  PRIMARY KEY (`id_movie`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`character_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`character_movie` (
  `id_character_movie` INT NOT NULL AUTO_INCREMENT,
  `character_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id_character_movie`),
  INDEX `id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `id_idx1` (`character_id` ASC) VISIBLE,
  CONSTRAINT `character_id`
    FOREIGN KEY (`character_id`)
    REFERENCES `disney`.`character` (`id_character`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `disney`.`movie` (`id_movie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`genre` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `id_movie` INT NOT NULL,
  PRIMARY KEY (`id_genre`),
  INDEX `id_idx` (`id_movie` ASC) VISIBLE,
  CONSTRAINT `id_movie_genre`
    FOREIGN KEY (`id_movie`)
    REFERENCES `disney`.`movie` (`id_movie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(500) NULL DEFAULT NULL,
  `token` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
